- gz_topic_name: "/world/empty/clock"
  ros_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- gz_topic_name: "/world/empty/model/rover_robo/joint_state"
  ros_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- gz_topic_name: "/model/rover_robo/tf"
  ros_topic_name: "/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/model/rover_robo/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- gz_topic_name: "/imu"
  gz_type_name: "gz.msgs.IMU"
  ros_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  direction: GZ_TO_ROS

- gz_topic_name: "/navsat"
  gz_type_name: "gz.msgs.NavSat"
  ros_topic_name: "/gps"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  direction: GZ_TO_ROS
