pointcloud_to_laserscan_node:
  ros__parameters:
    target_frame: base_link
    transform_tolerance: 0.01
    min_height: 0.0
    max_height: 1.0
    angle_min: -1.57
    angle_max: 1.57
    angle_increment: 0.0087
    scan_time: 0.033
    range_min: 0.45
    range_max: 10.0
    use_inf: true
    input_pointclud_topic: /camera/images/points
    output_scan_topic: /scan
